# See https://domluna.github.io/JuliaFormatter.jl/stable/ for a list of options
style = "sciml"
align_assignment = true
align_struct_field = true
align_conditional = true
align_pair_arrow = true
align_matrix = true